# Generated by Django 3.2.4 on 2021-06-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lastName',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='firstName',
            field=models.TextField(),
        ),
    ]
