# Generated by Django 3.2.4 on 2021-06-29 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_imageproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='image'),
        ),
    ]
