# Generated by Django 3.2.4 on 2021-06-29 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suplayer', '0002_remove_suplayer_product'),
        ('product', '0006_alter_imageproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='suplayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suplayerProduct', to='suplayer.suplayer', verbose_name='suplayer'),
        ),
    ]
