# Generated by Django 3.2.4 on 2021-06-29 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suplayer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suplayer',
            name='product',
        ),
    ]
