# Generated by Django 3.2.4 on 2021-06-29 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('keywords', '0002_auto_20210627_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywords',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='category.category', verbose_name='cat'),
        ),
    ]
