# Generated by Django 3.2.4 on 2021-06-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('OrderNumber', models.CharField(max_length=100)),
                ('OrderDate', models.DateTimeField(auto_now_add=True)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('AdresseLivraison', models.TextField(null=True)),
                ('Note', models.TextField(null=True)),
                ('ModePaiement', models.TextField(null=True)),
                ('datePrevueLivraison', models.DateTimeField()),
                ('isCancled', models.BooleanField(null=True)),
                ('lastName', models.TextField(null=True)),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('password', models.TextField()),
                ('adresse', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
