# Generated by Django 3.2.4 on 2021-06-30 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_suplayer'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Quantity', models.IntegerField()),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderFK', to='order.order', unique=True, verbose_name='order')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderFK', to='product.product', unique=True, verbose_name='order')),
            ],
        ),
    ]
